<a href="https://colab.research.google.com/github/Vitalyastiy/cheat/blob/main/Basics_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Основы NumPy
<hr>

**Основа NymPy** -  это объект **ndarray**, который используется для представления **N-мерного массива**; это быстрый и гибкий контейнер для хранения большим наборов данных в Python. Массивы позволяют выполнять математические перации над целыми блоками данных. По сути это обычный list с большим набором возможностей. 

У любого **numpy-массива (array)** есть атрибут **shape** - кортеж, описывающий размер по каждому измерению, и атрибут
**dtype** - объект, описывающий тип данных в массив; **ndim** - количество измерений массива (одномерный, двухмерный и т.д.). **tolist()** - конвертирует array в обычный python list

**Array vs list:**
* Array используют меньше памяти, чем списки
* Array обладают значительно большей функциональностью
* Array требуют, чтобы данные были однородными; списки нет


## **1D (одномерные массивы, списки, векторы), 2D (двумерные массивы, матрицы) и 3D (куб)-arrays:**

![%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-2.png](attachment:%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-2.png)

Четырехмерный, пятимерный и более массив — это **тензор**.

## Работа с NumPy

In [1]:
import numpy as np

In [2]:
data = [1, 2, 3, 4, 5]

arr = np.array(data) # создание из list

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
(5,)
int64
1


**Типы данных NumPy:**

* np.int64          // Signed 64-bit integer types
* np.float32        // Standard double-precision floating point
* np.complex        // Complex numbers represented by 128 floats>
* np.bool           // Boolean type storing TRUE and FALSE values
* np.object         // Python object type
* np.string_        // Fixed-length string type>
* np.unicode_       // Fixed-length unicode type

In [3]:
arr2 = np.array([1, 2, 3, 4, 5])  

print(arr2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)

[1 2 3 4 5]
(5,)
int64
1


In [4]:
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float) # задаём явно тип данных

print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)
print(len(arr3))
print(arr3.size)

[1. 2. 3. 4. 5.]
(5,)
float64
1
5
5


<ipython-input-4-131268a0ef5c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float) # задаём явно тип данных


In [5]:
arr3 = arr3.astype(np.int64) # приводим все элементы к типу int64

print(arr3)
print(arr3.dtype)

[1 2 3 4 5]
int64


In [6]:
arr4 = np.arange(0, 20, 1.5) 

arr4

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [8]:
arr5 = np.linspace(0, 2, 5) # 5 чисел от 0 до 2

arr5

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
arr5 = np.linspace(0, 2, 50)

arr5

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [12]:
random_arr = np.random.random((5,))

random_arr

array([0.77733491, 0.82199922, 0.75013492, 0.52762692, 0.73411661])

In [13]:
random_arr2 = np.random.random_sample((5,))
random_arr2

array([0.76265877, 0.52594754, 0.94436057, 0.00759749, 0.43743745])

### Диапазон случайных чисел от [a,b]: (b - a) * np.random() + a, где b > a

In [14]:
# 5 случайных значений от -5 до 10
random_arr3 = (10 - -5) * np.random.random_sample((5,)) - 5
random_arr3

array([9.42588759, 0.61514268, 5.05877265, 3.2198165 , 3.30708408])

## Операции

In [18]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.sqrt(arr)
print(arr)

arr = np.sin(arr)
print(arr)

arr = np.cos(arr)
print(arr)

arr = np.log(arr)
print(arr)

arr = np.exp(arr)
print(arr)

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.84147098 0.98776595 0.98702664 0.90929743 0.78674913]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]
[-0.40591509 -0.59682621 -0.59570612 -0.48727141 -0.34792639]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]


In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [20]:
c = a + b # np.add(a, b)

print(c)

[ 7  9 11 13 15]


In [21]:
a * b # np.multiply(a,b)

array([ 6, 14, 24, 36, 50])

In [22]:
a - b # np.subtract

array([-5, -5, -5, -5, -5])

In [23]:
a / b #np.divide

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2  # все элементы умножить на 2
print(arr)

[ 2  4  6  8 10]


In [25]:
arr = arr ** 2  # возводим все элементы в квадрат 
arr

array([  4,  16,  36,  64, 100])

In [ ]:
simple_list = [1, 2, 3, 4, 5]
simple_list = simple_list * 2
print(simple_list)

simple_list = simple_list ** 2

## Функции агрегаты

In [30]:
arr = np.random.randint(-5, 25, 10)
arr

array([13, 20,  5, 18,  9, 19, -5, 23, -5, 14])

In [34]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.median(arr))

23
-5
11.1
111
9.502105029939418
13.5


In [35]:
arr < 2

array([False, False, False, False, False, False,  True, False,  True,
       False])

## Манипуляции с массивами

In [36]:
np.insert(arr, 2, -20) # вставляем 20 в позицию 2 

array([ 13,  20, -20,   5,  18,   9,  19,  -5,  23,  -5,  14])

In [37]:
np.delete(arr, 2) # удаляем элемент во 2 позиции, с матрицами можно укзывать строки или столбцы 

array([13, 20, 18,  9, 19, -5, 23, -5, 14])

In [38]:
np.sort(arr)

array([-5, -5,  5,  9, 13, 14, 18, 19, 20, 23])

In [39]:
arr2 = np.array([0, 0, 0])
arr = np.concatenate((arr, arr2))
arr

array([13, 20,  5, 18,  9, 19, -5, 23, -5, 14,  0,  0,  0])

In [40]:
np.array_split(arr, 3) #hsplit, vsplit

[array([13, 20,  5, 18,  9]), array([19, -5, 23, -5]), array([14,  0,  0,  0])]

## Индексы и одномерные массивы 

In [41]:
arr = np.array([1, -2, 3, -4, 5])
arr[0] = 0
print(arr[2])
print(arr[0:2])
print(arr[::-1])
print(arr[arr < 2])
print(arr[(arr < 2) & (arr > 0)])
print(arr[(arr > 4) | (arr < 0)])
arr[1:4] = 0
print(arr)

3
[ 0 -2]
[ 5 -4  3 -2  0]
[ 0 -2 -4]
[]
[-2 -4  5]
[0 0 0 0 5]


## Матрицы и многомерные массивы

In [42]:
matrix = np.array([(1,2,3),(4,5,6)], dtype=np.float64)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
matrix = np.array([(1,2,3),(4,5,6), (7, 8, 9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matrix = np.array([(1,2,3),(4,5,6),(7, 8, 9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a_3d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
matrix = np.array([(1,2,3),(4,5,6), (7, 8, 9)])
matrix
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)

(3, 3)
2
9


In [48]:
matrix.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
matrix = np.array([(1,2,3),(4,5,6), (7, 8, 9), (10, 11, 12)])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
matrix2 = np.random.random((2,2))
matrix2

array([[0.41365582, 0.40927548],
       [0.63274006, 0.74195186]])

In [52]:
print(matrix)
matrix = np.resize(matrix, (2,2))
print()
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2]
 [3 4]]


In [57]:
new_matrix = np.arange(16).reshape(2,8)
new_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## Создание специальных матриц

In [67]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [71]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Операции над матрицами

In [72]:
matrix1 = np.array([(1, 2), (3, 4)])
print(matrix1)
print()
matrix2 = np.array([(5, 6), (7, 8)])
print(matrix2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [73]:
matrix1 + matrix2 # np.add

array([[ 6,  8],
       [10, 12]])

In [74]:
matrix1 - matrix2

array([[-4, -4],
       [-4, -4]])

In [75]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 32]])

In [76]:
matrix1 / matrix2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [77]:
matrix1.dot(matrix2) # скалаярное произведение

array([[19, 22],
       [43, 50]])

**Axis** - ось. 0 -  ось строк, 1 - ось столбцов

https://i.stack.imgur.com/gj5ue.jpg

In [78]:
matrix = np.array([(1,2,3), (4, 5, 6), (7, 8,9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.delete(matrix,1,axis=0) # удаляет 1 строку матрицы

array([[1, 2, 3],
       [7, 8, 9]])

In [80]:
np.delete(matrix,1,axis=1) # удаляет 1 столбец матрицы

array([[1, 3],
       [4, 6],
       [7, 9]])

In [81]:
np.sin(matrix)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [82]:
np.log(matrix)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

При применении определенных функций Numpy, таких как np.mean (),max() и т.д. мы можем указать, по какой оси мы хотим вычислять значения.

Для axis = 0 это означает, что мы применяем функцию к каждому «столбцу» или ко всем значениям, которые встречаются по вертикали.

Для axis = 1 это означает, что мы применяем функцию к каждой «строке» или ко всем значениям по горизонтали.

In [83]:
matrix.sum()

45

In [84]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
print(matrix.max())
print(matrix.max(axis=0)) # ищем наибольший элемент по каждой строке

9
[7 8 9]


In [86]:
np.mean(matrix, axis=0) # среднее значение идёт по строкам (1 + 4 + 7)/3 = 4

array([4., 5., 6.])

In [87]:
np.mean(matrix, axis=1) # среднее значение идёт по столбцам (1 + 2 + 3)/3 = 2

array([2., 5., 8.])

In [94]:
matrix**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [93]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr1)
print()
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
print(arr2)
print()
arr = np.concatenate((arr1,arr2),axis=1) # добавляем arr2 к arr1 как столбцы
arr

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]



array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [97]:
arr = np.concatenate((arr1,arr2),axis=0) # добавляем arr2 к arr1 как строки
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [99]:
arr = np.vstack((arr1,arr2))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
np.split(arr,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [101]:
np.split(arr,2, axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [102]:
np.split(arr,3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [104]:
np.append(arr, np.array([1, 2, 3]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3])

## Индексация

In [105]:
matrix = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
matrix[1,2] # 2 элемент 1 строки

6

In [107]:
matrix[2] # 2 строка

array([7, 8, 9])

In [108]:
matrix[:,2] # 2 столбец

array([3, 6, 9])

In [109]:
matrix[1:3, 0:2] # 0 и 1 столбец, 1  и 2 строки

array([[4, 5],
       [7, 8]])

In [110]:
matrix[matrix > 2]

array([3, 4, 5, 6, 7, 8, 9])

# Специальные операции

In [111]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
matrix.T  # транспонированная 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [113]:
matrix.flatten() # в массив 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.linalg.inv(matrix) # обратная матрица 

LinAlgError: ignored

In [115]:
np.trace(matrix) # след матрицы

15

In [116]:
np.linalg.det(matrix) # определитель

0.0

In [117]:
np.linalg.matrix_rank(matrix) # ранк

2

In [118]:
eigenvalues, eigenvectors = np.linalg.eig(matrix) # собственные числа и векторы 
print(eigenvalues)
print()
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Доп возможности

In [119]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible wi

In [120]:
np.loadtxt('file.txt') # загрузка из текстовог офайла 
np.genfromtxt('file.csv',delimiter=',') # загрузка из csv офайла 
np.savetxt('file.txt',arr,delimiter=' ') # запись в  текстовый файл 
np.savetxt('file.csv',arr,delimiter=',') # запись в  csv файл 

OSError: ignored

## Полезные ссылки

https://www.dataquest.io/blog/numpy-cheat-sheet/
    
https://vk.com/doc114954319_556487793?hash=a4aeb3c8f00331ca46&dl=ce3a2e019cd32c83ee
    
https://towardsdatascience.com/numpy-cheat-sheet-4e3858d0ff0e